# main text of home
name: Illustrated Glossary of P훮li Terms

description: P훮li language glossary and dictionary with examples from the Therav훮da P훮li Canon.

# if it's an external image, update below for true
# better with square images
external-image: false
picture: assets/images/profile.jpg

url: https://pali-glossary.github.io

permalink: /:title/

email: pali.glossary@gmail.com

authors:
    aj-varado:
        name: Ajahn Varado
        bio: Venerable Varado was ordained in 1988 as a bhikkhu in Chithurst Buddhist Monastery, England, by Venerable Ajahn Sumedho.
        external-image: false
        picture: assets/images/profile.jpg

# do you want a larger site? change the option below
# options: [normal, large] | default: normal
# normal = 560px / large = 810px
width: large

# if you don't want comments in your posts, leave categories empty
disqus:
  shortname: mydisqus # enter this from your disqus account
  categories: [] # only show disqus for posts that have these categories

about: false
resume: false
projects: false
blog: false
read-time: false
show-tags: false
related: false

# Display links for next and previous posts for the specified categories
post-advance-links: []

show-author: false

# do you want some animations?
animation: true

plugins:
  - jekyll-seo-tag
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-admin

jekyll-mentions:
    base_url: https://github.com
